// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPkgcJR_eeQmX8M9UO12SiLTYLMxc4wtc',
    appId: '1:55060102370:web:145f99a946012ff971f2bb',
    messagingSenderId: '55060102370',
    projectId: 'futter-app-a0120',
    authDomain: 'futter-app-a0120.firebaseapp.com',
    storageBucket: 'futter-app-a0120.firebasestorage.app',
    measurementId: 'G-5YQBWNFZE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw4SDjLpdqATl0UXnD9DQAOKb1MMmI-E4',
    appId: '1:55060102370:android:17885e2b7655f3f571f2bb',
    messagingSenderId: '55060102370',
    projectId: 'futter-app-a0120',
    storageBucket: 'futter-app-a0120.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3b880OA7mSI0_0TzxBsIYQtLJMIkeXPI',
    appId: '1:55060102370:ios:737d5c08e26e426d71f2bb',
    messagingSenderId: '55060102370',
    projectId: 'futter-app-a0120',
    storageBucket: 'futter-app-a0120.firebasestorage.app',
    iosBundleId: 'com.example.whatEatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3b880OA7mSI0_0TzxBsIYQtLJMIkeXPI',
    appId: '1:55060102370:ios:737d5c08e26e426d71f2bb',
    messagingSenderId: '55060102370',
    projectId: 'futter-app-a0120',
    storageBucket: 'futter-app-a0120.firebasestorage.app',
    iosBundleId: 'com.example.whatEatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPkgcJR_eeQmX8M9UO12SiLTYLMxc4wtc',
    appId: '1:55060102370:web:59900c3f45a8ab3071f2bb',
    messagingSenderId: '55060102370',
    projectId: 'futter-app-a0120',
    authDomain: 'futter-app-a0120.firebaseapp.com',
    storageBucket: 'futter-app-a0120.firebasestorage.app',
    measurementId: 'G-2XZRSP31XX',
  );
}
